export const LOGIN_AUTH = 'LOGIN_AUTH'
export const SIGNUP_AUTH = 'SIGNUP_AUTH'
export const LOGOUT_AUTH = 'LOGOUT_AUTH'
export const CREATE_DAY = 'CREATE_DAY'
export const DELETE_DAY = 'DELETE_DAY'
export const EDIT_DAY = 'EDIT_DAY'
export const CREATE_BAND = 'CREATE_BAND'
export const DELETE_BAND = 'DELETE_BAND'
export const EDIT_BAND = 'EDIT_BAND'
export const DAYS_LIST = 'DAYS_LIST'

